# CI script for KoraOS on Gitlab
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
image: gcc

build:
  stage: build
  before_script:
    - apt update && apt install -y libcairo2-dev
  script:
    - make

